In [1]:
import numpy as np

In [8]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

[1 2 3 4 5] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
#create
arr1=np.zeros((2,3),dtype="int64")
print(arr1)

arr2=np.ones((2,3),dtype="int64")
print(arr2)

arr2=np.full((2,3),100) #prefill with values
print(arr2)

arr3=np.eye(3) #indentity matrix
print(arr3)

arr4=np.arange(1,10) #range elements
print(arr4)

arr5=np.linspace(1,100,4) #evenely spaced arrays
print(arr5)



[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[100 100 100]
 [100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 2 3 4 5 6 7 8 9]
[  1.  34.  67. 100.]


In [42]:
#Properties

arr=np.array([[1,2,3,4,5],[7,8,9,10,11]])
print(arr.shape) #dimensions=nXm
print(arr.size)#total elements
print(arr.dtype) 
print(arr.ndim) #number of dimensions

float_arr=arr.astype(np.float64)
print(float_arr)

(2, 5)
10
int32
2
[[ 1.  2.  3.  4.  5.]
 [ 7.  8.  9. 10. 11.]]


In [48]:
#Operations on Array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

reshaped=arr.reshape((3,2))
print(reshaped)

flattened=arr.flatten() #2D-->1D
print(flattened)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [61]:
#Indexing
# arr=np.array([1,2,3,4,5])
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0][3])

#Fancy Indexing
arr1=np.array([1,2,3,4,5])
idx=[0,1,2]
print(arr1[idx])

4
[1 2 3]


In [3]:
#Slicing
arr=np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


In [11]:
#Multi Dimensional Arrays
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns=np.sum(arr2D,axis=0)
print(sum_of_columns)

sum_of_rows=np.sum(arr2D,axis=1)
print(sum_of_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [15]:
#3D Array

arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])

print(arr3D)
#indexing

print(arr3D[0,1,1])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
4


In [17]:
#Vectorization-->Performing operation on entire arrays at once instead of using python loop

arr=np.array([1,2,3,4,5])

print(arr ** 2)

[ 1  4  9 16 25]


In [19]:
#BroadCasting-->allows arrays of different shapes to be used together in arithmetic operations without explicitly copying data

print(arr+5)


[ 6  7  8  9 10]


In [25]:
#normalize

arr=np.array([[1,2],[3,4]])

mean=np.mean(arr)
std_dev=np.std(arr)

normalised_arr=(arr-mean)/std_dev
print(normalised_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [43]:
#Mathematical Function

#aggregation fnx

arr=np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) #returns index of minimum value
print(np.argmax(arr)) #returns index of maximum value
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [71]:
#power fnx

arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr,3))

#log fnx

print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

#rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr=np.array([1,2,4,5,5,6,2,3,8,8,9,-1,-1,-4,-4,-10])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
3.0
4.0
3.0
3.0
[-10  -4  -1   1   2   3   4   5   6   8   9]
[-10  -4  -4  -1  -1   1   2   2   3   4   5   5   6   8   8   9]
[ 1  2  4  5  5  6  2  3  8  8  9  1  1  4  4 10]
